In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
DATA_PATH_SINHVIEN_RAW = '/content/drive/MyDrive/Nhóm 6 - DS317.P11/ĐỒ ÁN MÔN HỌC/2.dataset_raw/01.sinhvien_raw.csv'
DATA_PATH_THI_SINH_RAW = '/content/drive/MyDrive/Nhóm 6 - DS317.P11/ĐỒ ÁN MÔN HỌC/2.dataset_raw/05.ThiSinh.xlsx'

In [4]:
df_sinhvien = pd.read_csv(DATA_PATH_SINHVIEN_RAW)
df_thi_sinh = pd.read_excel(DATA_PATH_THI_SINH_RAW)

In [5]:
# Create a new column to group all other categories into 'OTHER'
df_thi_sinh['encoded_column'] =df_thi_sinh['dien_tt'].apply(lambda x: x if x in ['THPT', 'ĐGNL'] else 'OTHER')

# Perform one-hot encoding
encoded_columns = pd.get_dummies(df_thi_sinh['encoded_column'], prefix='', prefix_sep='')

# Add the encoded columns to the original DataFrame
df = pd.concat([df_thi_sinh, encoded_columns], axis=1)

In [6]:
# Replace True with 1 and False with 0
df = df.replace({True: 1, False: 0})

<ipython-input-6-adf8d3fd0fe8>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({True: 1, False: 0})

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mssv            8234 non-null   object
 1   dien_tt         8234 non-null   object
 2   diem_tt         8104 non-null   float64
 3   lop12_matinh    6060 non-null   float64
 4   lop12_matruong  6061 non-null   float64
 5   TEN_TRUONG      6060 non-null   object
 6   encoded_column  8234 non-null   object
 7   OTHER           8234 non-null   int64
 8   THPT            8234 non-null   int64
 9   ĐGNL            8234 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 643.4+ KB

In [8]:
df.drop(columns = ['dien_tt','lop12_matinh','lop12_matruong','TEN_TRUONG','encoded_column'],inplace = True)

In [9]:
df.isnull().sum()

mssv         0
diem_tt    130
OTHER        0
THPT         0
ĐGNL         0
dtype: int64

In [10]:
df_tabular = pd.merge(df, df_sinhvien, on='mssv', how='inner')

In [11]:
df_tabular.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 50 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   mssv                       8234 non-null   object
 1   diem_tt                    8104 non-null   float64
 2   OTHER                      8234 non-null   int64
 3   THPT                       8234 non-null   int64
 4   ĐGNL                       8234 non-null   int64
 5   id                         8234 non-null   float64
 6   namsinh                    8234 non-null   float64
 7   gioitinh                   8234 non-null   float64
 8   lopsh                      8234 non-null   object
 9   khoahoc                    8234 non-null   float64
 10  tinhtrang                  8234 non-null   float64
 11  noisinh_đc0                8234 non-null   int64
 12  noisinh_đc1                8234 non-null   int64
 13  noisinh_đc2                8234 non-null   int64
 14  noisinh_đc3                8234 non-null   int64
 15  noisinh_đc4                8234 non-null   int64
 16  noisinh_đc5                8234 non-null   int64
 17  noisinh_đc6                8234 non-null   int64
 18  name_cn2                   8234 non-null   object
 19  hedt_CLC                   8234 non-null   int64
 20  hedt_CNTN                  8234 non-null   int64
 21  hedt_CQUI                  8234 non-null   int64
 22  hedt_CTTT                  8234 non-null   int64
 23  hedt_KSTN                  8234 non-null   int64
 24  khoa_CNPM                  8234 non-null   int64
 25  khoa_HTTT                  8234 non-null   int64
 26  khoa_KHMT                  8234 non-null   int64
 27  khoa_KTMT                  8234 non-null   int64
 28  khoa_KTTT                  8234 non-null   int64
 29  khoa_MMT&TT                8234 non-null   int64
 30  chuyennganh2_7340122_CLC   8234 non-null   int64
 31  chuyennganh2_7340122_CQ    8234 non-null   int64
 32  chuyennganh2_7480101_CLC   8234 non-null   int64
 33  chuyennganh2_7480101_CQ    8234 non-null   int64
 34  chuyennganh2_7480101_CTTN  8234 non-null   int64
 35  chuyennganh2_7480102_CLC   8234 non-null   int64
 36  chuyennganh2_7480102_CQ    8234 non-null   int64
 37  chuyennganh2_7480103_CLC   8234 non-null   int64
 38  chuyennganh2_7480103_CQ    8234 non-null   int64
 39  chuyennganh2_7480104_CLC   8234 non-null   int64
 40  chuyennganh2_7480104_CQ    8234 non-null   int64
 41  chuyennganh2_7480104_CTTT  8234 non-null   int64
 42  chuyennganh2_7480106_CLC   8234 non-null   int64
 43  chuyennganh2_7480106_CQ    8234 non-null   int64
 44  chuyennganh2_7480109_CQ    8234 non-null   int64
 45  chuyennganh2_7480201_CLC   8234 non-null   int64
 46  chuyennganh2_7480201_CQ    8234 non-null   int64
 47  chuyennganh2_7480202_CLC   8234 non-null   int64
 48  chuyennganh2_7480202_CQ    8234 non-null   int64
 49  chuyennganh2_7480202_CTTN  8234 non-null   int64
dtypes: float64(6), int64(41), object(3)
memory usage: 3.1+ MB

In [12]:
df_tabular.drop(columns = ['id','namsinh','gioitinh','khoahoc','tinhtrang','lopsh','name_cn2'],inplace = True)

In [13]:
df_tabular_clean = pd.read_csv('/content/drive/MyDrive/Nhóm 6 - DS317.P11/ĐỒ ÁN MÔN HỌC/3.data_processing/data-final/tabular_lstm/tabular_lstm_clean.csv')

In [14]:
df_tabular_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5181 entries, 0 to 5180
Data columns (total 82 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   mssv                       5181 non-null   object
 1   diem_tt                    5181 non-null   float64
 2   OTHER                      5181 non-null   int64
 3   THPT                       5181 non-null   int64
 4   ĐGNL                       5181 non-null   int64
 5   chuyennganh2_7340122_CLC   5181 non-null   int64
 6   chuyennganh2_7340122_CQ    5181 non-null   int64
 7   chuyennganh2_7480101_CLC   5181 non-null   int64
 8   chuyennganh2_7480101_CQ    5181 non-null   int64
 9   chuyennganh2_7480101_CTTN  5181 non-null   int64
 10  chuyennganh2_7480102_CLC   5181 non-null   int64
 11  chuyennganh2_7480102_CQ    5181 non-null   int64
 12  chuyennganh2_7480103_CLC   5181 non-null   int64
 13  chuyennganh2_7480103_CQ    5181 non-null   int64
 14  chuyennganh2_7480104_CLC   5181 non-null   int64
 15  chuyennganh2_7480104_CQ    5181 non-null   int64
 16  chuyennganh2_7480104_CTTT  5181 non-null   int64
 17  chuyennganh2_7480106_CLC   5181 non-null   int64
 18  chuyennganh2_7480106_CQ    5181 non-null   int64
 19  chuyennganh2_7480109_CQ    5181 non-null   int64
 20  chuyennganh2_7480201_CLC   5181 non-null   int64
 21  chuyennganh2_7480201_CQ    5181 non-null   int64
 22  chuyennganh2_7480202_CLC   5181 non-null   int64
 23  chuyennganh2_7480202_CQ    5181 non-null   int64
 24  chuyennganh2_7480202_CTTN  5181 non-null   int64
 25  hedt_CLC                   5181 non-null   int64
 26  hedt_CNTN                  5181 non-null   int64
 27  hedt_CQUI                  5181 non-null   int64
 28  hedt_CTTT                  5181 non-null   int64
 29  hedt_KSTN                  5181 non-null   int64
 30  khoa_CNPM                  5181 non-null   int64
 31  khoa_HTTT                  5181 non-null   int64
 32  khoa_KHMT                  5181 non-null   int64
 33  khoa_KTMT                  5181 non-null   int64
 34  khoa_KTTT                  5181 non-null   int64
 35  khoa_MMT&TT                5181 non-null   int64
 36  noisinh_0                  5181 non-null   int64
 37  noisinh_1                  5181 non-null   int64
 38  noisinh_2                  5181 non-null   int64
 39  noisinh_3                  5181 non-null   int64
 40  noisinh_4                  5181 non-null   int64
 41  noisinh_5                  5181 non-null   int64
 42  noisinh_6                  5181 non-null   int64
 43  sem1                       5181 non-null   float64
 44  sem2                       5181 non-null   float64
 45  sem3                       5181 non-null   float64
 46  sem4                       5181 non-null   float64
 47  sem5                       5181 non-null   float64
 48  sem6                       5181 non-null   float64
 49  sem7                       5181 non-null   float64
 50  sem8                       5181 non-null   float64
 51  sem9                       5181 non-null   float64
 52  sem10                      5181 non-null   float64
 53  sem11                      5181 non-null   float64
 54  sem12                      5181 non-null   float64
 55  sem13                      5181 non-null   float64
 56  sem14                      5181 non-null   float64
 57  sem15                      5181 non-null   float64
 58  sem16                      5181 non-null   float64
 59  sem17                      5181 non-null   float64
 60  sem18                      5181 non-null   float64
 61  sem19                      5181 non-null   float64
 62  sem20                      5181 non-null   float64
 63  sem21                      5181 non-null   float64
 64  sem22                      5181 non-null   float64
 65  term 1                     5181 non-null   float64
 66  term 2                     5181 non-null   float64
 67  term 3                     5181 non-null   float64
 68  term 4                     5181 non-null   float64
 69  term 5                     5181 non-null   float64
 70  term 6                     5181 non-null   float64
 71  term 7                     5181 non-null   float64
 72  term 8                     5181 non-null   float64
 73  term 9                     5181 non-null   float64
 74  term 10                    5181 non-null   float64
 75  term 11                    5181 non-null   float64
 76  term 12                    5181 non-null   float64
 77  term 13                    5181 non-null   float64
 78  term 14                    5181 non-null   float64
 79  term 15                    5181 non-null   float64
 80  term 16                    5181 non-null   float64
 81  label                      5181 non-null   int64
dtypes: float64(39), int64(42), object(1)
memory usage: 3.2+ MB

In [15]:
df_tabular.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   mssv                       8234 non-null   object
 1   diem_tt                    8104 non-null   float64
 2   OTHER                      8234 non-null   int64
 3   THPT                       8234 non-null   int64
 4   ĐGNL                       8234 non-null   int64
 5   noisinh_đc0                8234 non-null   int64
 6   noisinh_đc1                8234 non-null   int64
 7   noisinh_đc2                8234 non-null   int64
 8   noisinh_đc3                8234 non-null   int64
 9   noisinh_đc4                8234 non-null   int64
 10  noisinh_đc5                8234 non-null   int64
 11  noisinh_đc6                8234 non-null   int64
 12  hedt_CLC                   8234 non-null   int64
 13  hedt_CNTN                  8234 non-null   int64
 14  hedt_CQUI                  8234 non-null   int64
 15  hedt_CTTT                  8234 non-null   int64
 16  hedt_KSTN                  8234 non-null   int64
 17  khoa_CNPM                  8234 non-null   int64
 18  khoa_HTTT                  8234 non-null   int64
 19  khoa_KHMT                  8234 non-null   int64
 20  khoa_KTMT                  8234 non-null   int64
 21  khoa_KTTT                  8234 non-null   int64
 22  khoa_MMT&TT                8234 non-null   int64
 23  chuyennganh2_7340122_CLC   8234 non-null   int64
 24  chuyennganh2_7340122_CQ    8234 non-null   int64
 25  chuyennganh2_7480101_CLC   8234 non-null   int64
 26  chuyennganh2_7480101_CQ    8234 non-null   int64
 27  chuyennganh2_7480101_CTTN  8234 non-null   int64
 28  chuyennganh2_7480102_CLC   8234 non-null   int64
 29  chuyennganh2_7480102_CQ    8234 non-null   int64
 30  chuyennganh2_7480103_CLC   8234 non-null   int64
 31  chuyennganh2_7480103_CQ    8234 non-null   int64
 32  chuyennganh2_7480104_CLC   8234 non-null   int64
 33  chuyennganh2_7480104_CQ    8234 non-null   int64
 34  chuyennganh2_7480104_CTTT  8234 non-null   int64
 35  chuyennganh2_7480106_CLC   8234 non-null   int64
 36  chuyennganh2_7480106_CQ    8234 non-null   int64
 37  chuyennganh2_7480109_CQ    8234 non-null   int64
 38  chuyennganh2_7480201_CLC   8234 non-null   int64
 39  chuyennganh2_7480201_CQ    8234 non-null   int64
 40  chuyennganh2_7480202_CLC   8234 non-null   int64
 41  chuyennganh2_7480202_CQ    8234 non-null   int64
 42  chuyennganh2_7480202_CTTN  8234 non-null   int64
dtypes: float64(1), int64(41), object(1)
memory usage: 2.7+ MB

In [16]:
import pandas as pd

# Assume `df` is your DataFrame
columns = list(df_tabular.columns)

# Extract noisinh columns (assuming they are named in a pattern)
noisinh_columns = [col for col in columns if col.startswith("noisinh_")]

# Remove noisinh columns from the original order
remaining_columns = [col for col in columns if col not in noisinh_columns]

# Determine the position where noisinh columns should be inserted
target_position = 36

# Insert noisinh columns at the target position
new_columns_order = (
    remaining_columns[:target_position] +
    noisinh_columns +
    remaining_columns[target_position:]
)

# Reorder the DataFrame columns
df_tabular = df_tabular[new_columns_order]

# Check the new column order
print(df_tabular.columns)

Index(['mssv', 'diem_tt', 'OTHER', 'THPT', 'ĐGNL', 'hedt_CLC', 'hedt_CNTN',
       'hedt_CQUI', 'hedt_CTTT', 'hedt_KSTN', 'khoa_CNPM', 'khoa_HTTT',
       'khoa_KHMT', 'khoa_KTMT', 'khoa_KTTT', 'khoa_MMT&TT',
       'chuyennganh2_7340122_CLC', 'chuyennganh2_7340122_CQ',
       'chuyennganh2_7480101_CLC', 'chuyennganh2_7480101_CQ',
       'chuyennganh2_7480101_CTTN', 'chuyennganh2_7480102_CLC',
       'chuyennganh2_7480102_CQ', 'chuyennganh2_7480103_CLC',
       'chuyennganh2_7480103_CQ', 'chuyennganh2_7480104_CLC',
       'chuyennganh2_7480104_CQ', 'chuyennganh2_7480104_CTTT',
       'chuyennganh2_7480106_CLC', 'chuyennganh2_7480106_CQ',
       'chuyennganh2_7480109_CQ', 'chuyennganh2_7480201_CLC',
       'chuyennganh2_7480201_CQ', 'chuyennganh2_7480202_CLC',
       'chuyennganh2_7480202_CQ', 'chuyennganh2_7480202_CTTN', 'noisinh_đc0',
       'noisinh_đc1', 'noisinh_đc2', 'noisinh_đc3', 'noisinh_đc4',
       'noisinh_đc5', 'noisinh_đc6'],
      dtype='object')

In [17]:
df_tabular.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   mssv                       8234 non-null   object
 1   diem_tt                    8104 non-null   float64
 2   OTHER                      8234 non-null   int64
 3   THPT                       8234 non-null   int64
 4   ĐGNL                       8234 non-null   int64
 5   hedt_CLC                   8234 non-null   int64
 6   hedt_CNTN                  8234 non-null   int64
 7   hedt_CQUI                  8234 non-null   int64
 8   hedt_CTTT                  8234 non-null   int64
 9   hedt_KSTN                  8234 non-null   int64
 10  khoa_CNPM                  8234 non-null   int64
 11  khoa_HTTT                  8234 non-null   int64
 12  khoa_KHMT                  8234 non-null   int64
 13  khoa_KTMT                  8234 non-null   int64
 14  khoa_KTTT                  8234 non-null   int64
 15  khoa_MMT&TT                8234 non-null   int64
 16  chuyennganh2_7340122_CLC   8234 non-null   int64
 17  chuyennganh2_7340122_CQ    8234 non-null   int64
 18  chuyennganh2_7480101_CLC   8234 non-null   int64
 19  chuyennganh2_7480101_CQ    8234 non-null   int64
 20  chuyennganh2_7480101_CTTN  8234 non-null   int64
 21  chuyennganh2_7480102_CLC   8234 non-null   int64
 22  chuyennganh2_7480102_CQ    8234 non-null   int64
 23  chuyennganh2_7480103_CLC   8234 non-null   int64
 24  chuyennganh2_7480103_CQ    8234 non-null   int64
 25  chuyennganh2_7480104_CLC   8234 non-null   int64
 26  chuyennganh2_7480104_CQ    8234 non-null   int64
 27  chuyennganh2_7480104_CTTT  8234 non-null   int64
 28  chuyennganh2_7480106_CLC   8234 non-null   int64
 29  chuyennganh2_7480106_CQ    8234 non-null   int64
 30  chuyennganh2_7480109_CQ    8234 non-null   int64
 31  chuyennganh2_7480201_CLC   8234 non-null   int64
 32  chuyennganh2_7480201_CQ    8234 non-null   int64
 33  chuyennganh2_7480202_CLC   8234 non-null   int64
 34  chuyennganh2_7480202_CQ    8234 non-null   int64
 35  chuyennganh2_7480202_CTTN  8234 non-null   int64
 36  noisinh_đc0                8234 non-null   int64
 37  noisinh_đc1                8234 non-null   int64
 38  noisinh_đc2                8234 non-null   int64
 39  noisinh_đc3                8234 non-null   int64
 40  noisinh_đc4                8234 non-null   int64
 41  noisinh_đc5                8234 non-null   int64
 42  noisinh_đc6                8234 non-null   int64
dtypes: float64(1), int64(41), object(1)
memory usage: 2.7+ MB

In [18]:
# Identify the noisinh columns
noisinh_columns = [col for col in df_tabular.columns if col.startswith("noisinh_đc")]

# Rename noisinh columns to noisinh_0, noisinh_1, etc.
rename_dict = {col: f"noisinh_{i}" for i, col in enumerate(noisinh_columns)}

# Apply renaming
df_tabular.rename(columns=rename_dict, inplace=True)

# Verify changes
print(df_tabular.columns)

Index(['mssv', 'diem_tt', 'OTHER', 'THPT', 'ĐGNL', 'hedt_CLC', 'hedt_CNTN',
       'hedt_CQUI', 'hedt_CTTT', 'hedt_KSTN', 'khoa_CNPM', 'khoa_HTTT',
       'khoa_KHMT', 'khoa_KTMT', 'khoa_KTTT', 'khoa_MMT&TT',
       'chuyennganh2_7340122_CLC', 'chuyennganh2_7340122_CQ',
       'chuyennganh2_7480101_CLC', 'chuyennganh2_7480101_CQ',
       'chuyennganh2_7480101_CTTN', 'chuyennganh2_7480102_CLC',
       'chuyennganh2_7480102_CQ', 'chuyennganh2_7480103_CLC',
       'chuyennganh2_7480103_CQ', 'chuyennganh2_7480104_CLC',
       'chuyennganh2_7480104_CQ', 'chuyennganh2_7480104_CTTT',
       'chuyennganh2_7480106_CLC', 'chuyennganh2_7480106_CQ',
       'chuyennganh2_7480109_CQ', 'chuyennganh2_7480201_CLC',
       'chuyennganh2_7480201_CQ', 'chuyennganh2_7480202_CLC',
       'chuyennganh2_7480202_CQ', 'chuyennganh2_7480202_CTTN', 'noisinh_0',
       'noisinh_1', 'noisinh_2', 'noisinh_3', 'noisinh_4', 'noisinh_5',
       'noisinh_6'],
      dtype='object')

In [19]:
df_clean = pd.read_csv('/content/drive/MyDrive/Nhóm 6 - DS317.P11/ĐỒ ÁN MÔN HỌC/3.data_processing/data-final/tabular_lstm/tabular_lstm_clean.csv')

In [20]:
df_tabular_final = df_tabular[df_tabular['mssv'].isin(df_clean['mssv'].unique())]

In [ ]:
df_tabular_final.to_csv('/content/drive/MyDrive/Nhóm 6 - DS317.P11/ĐỒ ÁN MÔN HỌC/3.data_processing/data-20-12-2024/tabular_data/tabular_data_raw.csv',index=False)